networks:
  norskNetwork:
    name: norsk-nw

services:
  norsk-studio:
    networks:
      - norskNetwork
    ports:
      - 8000:8000
    environment:
      # In Docker networking the name of the norsk server is norsk - not 127.0.0.1
      STUDIO_NORSK_HOST: norsk-media
      STUDIO_NORSK_INTERNAL_PREFIX: http://norsk-media:8080
