server:
  library:
    - '@norskvideo/norsk-studio-built-ins'
    - '@norskvideo/norsk-studio-source-switcher'
    - '@norskvideo/norsk-studio-aws'
    - '@norskvideo/norsk-studio-alpha'
    - '@norskvideo/norsk-studio-beta'
